version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  test:
    build: .
    depends_on:
      - app
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "run_tests.py"]